apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    openshift.io/component: controllers
    openshift.io/control-plane: "true"
  name: openshift-controller-manager
  namespace: openshift-controller-manager
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      openshift.io/component: controllers
      openshift.io/control-plane: "true"
  template:
    metadata:
      creationTimestamp: null
      labels:
        openshift.io/component: controllers
        openshift.io/control-plane: "true"
      name: openshift-controller-manager
    spec:
      containers:
      - args:
        - --config=/etc/origin/master/master-config.yaml
        - --v=0
        command:
        - hypershift
        - openshift-controller-manager
        image: openshift/origin:latest
        imagePullPolicy: IfNotPresent
        name: c
        ports:
        - containerPort: 8444
          hostPort: 8444
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8444
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          privileged: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/origin/master/
          name: master-config
        - mountPath: /etc/origin/cloudprovider/
          name: master-cloud-provider
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: openshift-controller-manager
      serviceAccountName: openshift-controller-manager
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /home/pweil/codebase/openshift/src/github.com/openshift/origin/openshift.local.clusterup/openshift-controller-manager
          type: ""
        name: master-config
      - hostPath:
          path: /etc/origin/cloudprovider
          type: ""
        name: master-cloud-provider
  templateGeneration: 1
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

